-- AlterEnum
ALTER TYPE "ShipmentProvider" ADD VALUE IF NOT EXISTS 'LEOPARDS';
ALTER TYPE "ShipmentProvider" ADD VALUE IF NOT EXISTS 'TCS';
ALTER TYPE "ShipmentProvider" ADD VALUE IF NOT EXISTS 'MNP';
ALTER TYPE "ShipmentProvider" ADD VALUE IF NOT EXISTS 'TRAX';
ALTER TYPE "ShipmentProvider" ADD VALUE IF NOT EXISTS 'POSTEX';
